package at.stefl.ptbridge.ptmp.multiuser;

public enum MultiuserInterfaceType {
	
	CONSOLE,
	COPPER_ETHERNET,
	COPPER_FAST_ETHERNET,
	COPPER_GIGABIT_ETHERNET,
	FIBER_FAST_ETHERNET,
	FIBER_GIGABIT_ETHERNET,
	SERIAL_BIG,
	SERIAL,
	ANALOG_PHONE,
	COAXIAL;
	
}